### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by ArnaudBelcour** [gecko984/supervenn#11]
Hi Fedor,

Thank you for this tool, it is very useful and well documented!

There is a typo error in the readme during the presentation of the [min_width_for_annotation](https://github.com/gecko984/supervenn#avoid-clutter-in-the-x-axis-annotations ) argument. The argument `widths_minmax_ratio` is used instead of `min_width_for_annotation` in the python code block.

**Comment by gecko984** [comment]
Hi Arnaud, thank you for your feedback! Fixed it
