### ISSUE TITLE
Add Zenodo so I can cite you

### ISSUE THREAD

**Issue by philastrophist** [gecko984/supervenn#13]
Upload to https://zenodo.org/ so I can cite Supervenn properly in a scientific paper. You get a badge for github as well!

**Comment by gecko984** [comment]
Hi Shaun,
I think I did it, could you check?  https://zenodo.org/record/4012442#.X0_ae9Zn1hE

**Comment by philastrophist** [comment]
Great! I’ll use that then. Put the badge in the Readme though!
