### ISSUE TITLE
Recommended parameters for visualizing supervenn with 9 large sets

### ISSUE THREAD

**Issue by jolespin** [gecko984/supervenn#16]
I'm trying out `supervenn` on a dataset I'm working on and noticed some gnarly overlap in the `ITEMS`. 

What are you recommended settings to visualize this? 

```python
from supervenn import supervenn
with plt.style.context("seaborn-white"):
    fig, ax = plt.subplots(figsize=(21,13))
    supervenn(sets, set_annotations, side_plots=True, ax=ax, chunks_ordering="occurence" )
```

![image](https://user-images.githubusercontent.com/9061708/93509266-56b9e500-f8d4-11ea-8753-1d08de7f705f.png)

**Comment by gecko984** [comment]
Hi Josh.
It's either min_width_for_annotations=600 or widths_minmax_ratio somwhere between 0.025 and 0.2 if you dont mind losing the exact sizes proportion

**Comment by gecko984** [comment]
and I'd at least try the default chunks_ordering

**Comment by jolespin** [comment]
I did that and it looks much better thanks. 

Is there an option for providing custom set colors or colormaps?  I'm working on a plot for a publication and trying out supervenn alongside some heatmaps and upsetplot.  Supervenn seems to be the most informative for sure and aesthetically pleasing too.

**Comment by gecko984** [comment]
sure, there is a 'color_cycle' argument. It's all in the README by the way.
If you're including supervenn plots into your publication, you can cite the software using the DOI from the badge at the top of README
I'd try to increase DPI to produce images of better quailty
