### ISSUE TITLE
Restriction on intersection degree

### ISSUE THREAD

**Issue by aseemk98** [gecko984/supervenn#17]
Is there a way to restrict the visualisation to a certain degree? For eg, I have 12 sets, visualising all of them together takes a lot of time and the graph is extremely dense to look at. Can I restrict the overlap degree to 3? That is, I'll see overlapts upto only 3 sets.

**Comment by gecko984** [comment]
Hi! Could you describe how that would look like? It's not clear to me
Can you show the image that is too dense?

**Comment by gecko984** [comment]
@aseemk98 hi Aseem, is this issue still relevant to you, or I can close it?

**Comment by gecko984** [comment]
No feedback so closing
