### ISSUE TITLE
Background color of set-unique elements?

### ISSUE THREAD

**Issue by mcolic** [gecko984/supervenn#21]
Is there / what is the difference between white and gray color of rows? - outside of the overlap chunks. If there is no difference, is there a way to assign a single color to the background, like all white or all grey? Thanks!

**Comment by gecko984** [comment]
Hi Medina,
There is no difference, it's just for readability. There is currently no way to disable this, but I can add an argumentb that controls it, if you want. Do you need to specify a colour, or do you want them just white?

**Comment by mcolic** [comment]
Hi Fedor, 
Thanks for a prompt response. Great, I would prefer them all just white. Thank you!

**Comment by gecko984** [comment]
Version 0.3.3 is out on PyPi, so you can upgrade your installation with `pip install -U supervenn`. The `supervenn` function now has an `alternating_background` argument
@mcolic

**Comment by gecko984** [comment]
I prefer the two-color version though, really helps me to visually parse what's going on :-)

**Comment by mcolic** [comment]
Great, thanks again!
