### ISSUE TITLE
How to change the colors of blocks ?

### ISSUE THREAD

**Issue by snijesh** [gecko984/supervenn#27]
![image](https://user-images.githubusercontent.com/25811390/145666821-8157b6d7-ee66-4dd5-8e75-b76eac14d96b.png)

How do I change colours from `'green', 'orange' and 'light blue'` to `'red', 'brown' and 'navy blue'` ?

**Comment by gecko984** [comment]
use color_cycle argument
```
supervenn(sets, ..., color_cycle=['red', 'brown', 'navy'])
```
