### ISSUE TITLE
Where can I find the resulting picture?

### ISSUE THREAD

**Issue by udavdasha** [gecko984/supervenn#3]
Perhaps I am doing something really stupid here, but I just wanted first to reproduce the very basic example first. I installed the package and created a python script with the following lines:
```python
from supervenn import supervenn
sets = [{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}]
supervenn(sets, side_plots=False)
```

Now I run it - and nothing happens! The script just terminates and I am unable to find resulting picture anywhere. What am I doing wrong?

**Comment by gecko984** [comment]
Most users do any plotting in Python using an interactive environment like Jupyter Notebook. But if for any reason you need it to be run as a script, you can do it as follows:
```python
import matplotlib.pyplot as plt
from supervenn import supervenn
sets = [{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}]
supervenn(sets, side_plots=False)
plt.savefig('image.png')
```
