### ISSUE TITLE
it is possible to have a thinner line between boxes

### ISSUE THREAD

**Issue by xihajun** [gecko984/supervenn#31]

**Comment by xihajun** [comment]
Thanks for such a nice tool, I wonder if it is possible to change the line width

**Comment by xihajun** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/25631641/146835919-c46c3bf2-87a1-489a-8859-0dc81b595658.png">

**Comment by xihajun** [comment]
because paper would need to fit into A4 page

**Comment by gecko984** [comment]
Hi, @xihajun, 
the following code seems to help:
```python
my_supervenn = supervenn([{1,2,3,4}, {2,3,4,5}, {3,4,5,6}])
plt.grid(True, linewidth=.1)
```
or if you need to change the grid width in the side plots as well
```python
my_supervenn = supervenn([{1,2,3,4}, {2,3,4,5}, {3,4,5,6}])
for ax in my_supervenn.axes.values():
    ax.grid(True, linewidth=.1)
```

But from what I see it seems to me that maybe grid line width might not be the root issue.  It looks like you're not using supervenn in an optimal way. Could you show me the code and full image?

**Comment by gecko984** [comment]
no answer so closing this issue

**Comment by xihajun** [comment]
Hi @gecko984 Thanks for that!

I think it solved my issue, but I forgot to reply!!

And my code is 
```
supervenn(sets_list, ['set1','set2','set3','set4',"set5","set6"], widths_minmax_ratio=0.4, fontsize=11, rotate_col_annotations=True, col_annotations_area_height=1.2, side_plots=False)
```

**Comment by gecko984** [comment]
@xihajun great, but could you show the whole image? I'm curious

**Comment by xihajun** [comment]
yes, so the case might be I have a quite large set?
<img width="494" alt="image" src="https://user-images.githubusercontent.com/25631641/153210484-99da862a-2b65-43fe-9f6b-c2ffee8aca26.png">

**Comment by gecko984** [comment]
Ah, I get it. You could try lower values for widthts_minmax_ratio
