### ISSUE TITLE
Can we fix the background colour to white only?

### ISSUE THREAD

**Issue by xihajun** [gecko984/supervenn#32]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/25631641/153089212-93401e5a-aad6-4842-9362-d53c5cb4942e.png">

for example set_1 has a different colour

**Comment by xihajun** [comment]
maybe something like that?
```
plt.rcParams['axes.facecolor'] = 'none'
```
Not working  (updated)

Another thing may I ask if it is possible to put the set_0, set_1, set_2 in the y axis

**Comment by xihajun** [comment]
```
from supervenn import supervenn
sets = [{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}]
labels = ['alice', 'bob', 'third party']
supervenn(sets,labels, side_plots=False, alternating_background=False)
```

This works

**Comment by gecko984** [comment]
> Another thing may I ask if it is possible to put the set_0, set_1, set_2 in the y axis

No, it's no possible, unfortunately. I think it would be impractical, as only very short annotations would fit

**Comment by xihajun** [comment]
> > Another thing may I ask if it is possible to put the set_0, set_1, set_2 in the y axis
> 
> No, it's no possible, unfortunately. I think it would be impractical, as only very short annotations would fit

Thanks for you reply! Alternatively, maybe we can set the label to "" and manually and y axis I guess?

**Comment by gecko984** [comment]
yep, that's a good idea, you'll have to do something like that:
```python
from supervenn import supervenn
import matplotliob.pyplot as plt
supervenn([{1, 2, 3}, {3, 4}])
plt.annotate(xy=(0, 0.5), text='set1', va='center', ha='right')
plt.annotate(xy=(0, 1.5), text='set2', va='center', ha='right')
plt.ylabel(None)
```

**Comment by xihajun** [comment]
> yep, that's a good idea, you'll have to do something like that:
> 
> ```python
> from supervenn import supervenn
> import matplotliob.pyplot as plt
> supervenn([{1, 2, 3}, {3, 4}])
> plt.annotate(xy=(0, 0.5), s='set1', va='center', ha='right')
> plt.annotate(xy=(0, 1.5), s='set2', va='center', ha='right')
> plt.ylabel(None)
> ```

Thank you so much for your advise!
