### ISSUE TITLE
got multiple values for keyword argument 'row_heights'

### ISSUE THREAD

**Issue by Stephan-Linzbach** [gecko984/supervenn#38]
Somehow the row_heights default value is set when the function is called. Rendering the if statement dealing with no given row_height useless. However, when i want to add a custom row_height it gives me this error: "TypeError: supervenn._plots.plot_binary_array() got multiple values for keyword argument 'row_heights'".
I think the issue is solvable by just deleting row 454.

**Comment by gecko984** [comment]
Hey Stephan, thanks for your issue, I haven't set foot in the code for a while , so at this point you may be more qualified in this code :)  So it seems that if row_heights is passed to supervenn(), we will still pass it in `**kw` in row 456. And if row_heights is not passed to supervenn(), then the default value is set in line 119, right?

I will fix it in the next couple of days

**Comment by Stephan-Linzbach** [comment]
Yes, i think you are correct. Thank you :) Very great work though!

**Comment by gecko984** [comment]
@Stephan-Linzbach hey Stephan, I finally fixed the issue, sorry for taking so long. I had to reconfigure my terminal access to my github, and I was procrastinating on it for all this time
