### ISSUE TITLE
[enhancement] have supervenn._plots.supervenn return data

### ISSUE THREAD

**Issue by srcoulombe** [gecko984/supervenn#4]
supervenn has already been super useful for my work, and having supervenn._plots.supervenn return `chunks` would allow for more downstream EDA.

**Comment by gecko984** [comment]
Yeah that's definitely in my plans, may do that in the next couple of weeks

**Comment by gecko984** [comment]
@srcoulombe Hi, it's done in 0.3.0, already on PyPi
https://github.com/gecko984/supervenn#inspect-the-chunks-contents
