### ISSUE TITLE
How to transform the super venn diagram to donut plot?

### ISSUE THREAD

**Issue by vis-yyin** [gecko984/supervenn#41]
Hi,
I found the super venn diagram very helpful as it can handle data with many sets. Is it possible to have a function to stretch and bend the rectangular plot to a donut plot (circular)?  Sometimes, a donut plot is visually more appealing. It doesn't require any rearrangement of the chunks or rows, maybe just changing from a Cartesian coordinate system to a ploar coordinate system.

Thanks!

**Comment by gecko984** [comment]
Hi, glad you find supervenn useful. I'm not aware of a way of doing it easily and currently have no plans to implement such a feature.
