### ISSUE TITLE
[Feature request] Take in an `ax` object like seaborn, networkx, and other matplotlib wrappers

### ISSUE THREAD

**Issue by jolespin** [gecko984/supervenn#7]
```python
from supervenn import supervenn
sets = [{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}]
with plt.style.context("seaborn-white"):
    fig, ax = plt.subplots()
    supervenn(sets, side_plots=False, ax=ax)
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# <ipython-input-61-9074a6cee262> in <module>
#       3 with plt.style.context("seaborn-white"):
#       4     fig, ax = plt.subplots()
# ----> 5     supervenn(sets, side_plots=False, ax=ax)

# ~/anaconda3/envs/soothsayer5_env/lib/python3.8/site-packages/supervenn/_plots.py in supervenn(sets, set_annotations, figsize, side_plots, chunks_ordering, sets_ordering, reverse_chunks_order, reverse_sets_order, max_bruteforce_size, seeds, noise_prob, side_plot_width, min_width_for_annotation, widths_minmax_ratio, side_plot_color, dpi, **kw)
#     323         effective_min_width_for_annotation = min_width_for_annotation
#     324 
# --> 325     plot_binary_array(
#     326         arr=composition_array,
#     327         row_annotations=set_annotations,

# TypeError: plot_binary_array() got multiple values for keyword argument 'ax'
```

Right now it's not practical to use these in a production setting because we can't integrate these into existing figures.

**Comment by gecko984** [comment]
Hi Josh, thanks for your input.
This is definitely a good idea. I used to think that it was imposiible to split an existing axis into four uneven-sized axes, which I need for the "side plots". But after reading your message I dug deeper and now I think I figured out how to do it. So probably will implement it in the next few days, stay tuned.

**Comment by gecko984** [comment]
@jolespin care for a code review? ;-) 
https://github.com/gecko984/supervenn/pull/8

**Comment by jolespin** [comment]
Yea! I'll try it out.  I'm pretty novice for some of the functionality of GitHub.  How can I install the version in the code review to try out in my conda environment?

**Comment by gecko984** [comment]
@jolespin you just append `@` + the branch name
`pip install --upgrade git+https://github.com/gecko984/supervenn@add_ax_argument`
If supervenn is not yet installed in the env, skip `--upgrade`

**Comment by jolespin** [comment]
Thanks for that install command.  Good to know for the future. 

I'm trying it now but I can't get it to load? It's definitely in my site packages which is weird...

![image](https://user-images.githubusercontent.com/9061708/89324880-d5b4d000-d63c-11ea-9ed5-0a11f007a611.png)

**Comment by gecko984** [comment]
@jolespin I think you just need to restart your notebook kernel after installation

**Comment by gecko984** [comment]
@jolespin Or maybe the issue is that pip that you ran from inside the notebook does not refer to your env's pip. You can check that by running `!which pip` from inside the notebook

**Comment by jolespin** [comment]
Looks good to me! Thanks for adding this. I tried it out with some native and 3rd party style sheets.  Great job and turn around on this.

```python
import matplotlib.pyplot as plt
import mplcyberpunk
from supervenn import supervenn

with plt.style.context("cyberpunk"):
    fig, axes = plt.subplots(figsize=(13,5), nrows=2)
    supervenn([{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}], side_plots=False, ax=axes[0])
    supervenn([{"A","B","C"}, {"C","D"}, {"D","E","F","G"}], side_plots=False, ax=axes[1])
```
![image](https://user-images.githubusercontent.com/9061708/89460735-9f9c4c80-d71f-11ea-83c4-033c4d0b1d7d.png)

With side plots:

```python
with plt.style.context("ggplot"):
    fig, axes = plt.subplots(figsize=(13,13), nrows=2)
    supervenn([{1, 2, 3, 4}, {3, 4, 5}, {1, 6, 7, 8}], side_plots=True, ax=axes[0])
    supervenn([{"A","B","C"}, {"C","D"}, {"D","E","F","G"}], side_plots=True, ax=axes[1])
```

![image](https://user-images.githubusercontent.com/9061708/89460817-c5295600-d71f-11ea-84c4-9ec81d4ef98c.png)

**Comment by jolespin** [comment]
However, I did find an inconsistency:  When you add the side plots, you can't access the `ax` object appropriately.


```python
with plt.style.context("ggplot"):
    fig, ax = plt.subplots(figsize=(13,3), nrows=1)
    supervenn([{"A","B","C"}, {"C","D"}, {"D","E","F","G"}], side_plots=False, ax=ax)
    ax.axvline(np.mean(axes[1].get_xlim()), color="red")
    
```
![image](https://user-images.githubusercontent.com/9061708/89461127-44b72500-d720-11ea-9663-5dc33cb0c0a7.png)

```python
with plt.style.context("ggplot"):
    fig, ax = plt.subplots(figsize=(13,3), nrows=1)
    supervenn([{"A","B","C"}, {"C","D"}, {"D","E","F","G"}], side_plots=True, ax=ax)
    ax.axvline(np.mean(axes[1].get_xlim()), color="red")
```

![image](https://user-images.githubusercontent.com/9061708/89461162-56003180-d720-11ea-8932-7dabd61271c4.png)

**Comment by gecko984** [comment]
It is because the ax thay you passed is split into four smaller axes - one for the main plot, two for side plots and one is left unused. Having access to these axes might be useful, even though the practical benefit isn't obvious to me. Anyway it looks like a separate issue.
I think the way to go is to implement it in the scope of https://github.com/gecko984/supervenn/issues/4. Like, the supervenn function returns a Supervenn object with attributes giving access to axes, chunks and whatever else might be useful to users.

**Comment by jolespin** [comment]
What if the output of the function was a collection of ax objects in a list?

**Comment by gecko984** [comment]
Probably in a dict so that it's clear which axis is which. But I also wanted to give users access to the chunks' content, so will return an object that will contain both.

**Comment by jolespin** [comment]
That makes a lot of sense.  I think seaborn does something similar with the clustermap output.  It has a bunch of ax objects in there and others as well.

**Comment by gecko984** [comment]
I'll have a look at it, thanks.

**Comment by gecko984** [comment]
hey @jolespin, if you look at your example images, you can notice that the grid lines are not visible in the bottom. I fixed that in the latest release, so if you plan to use supervenn with different plot styles, it's worth upgrading it.

**Comment by gecko984** [comment]
@jolespin hey Josh, I've added a returned object in 0.3.0, which gives access to chunks' contents and to axes of the plot. The new ersion is already on PyPi
https://github.com/gecko984/supervenn#inspect-the-chunks-contents
https://github.com/gecko984/supervenn#access-the-figure-and-axes-objects-of-the-plot

**Comment by jolespin** [comment]
This is awesome, I will make sure to update my environment.
